// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0j7rUIoFvnW7jEtX_JOiOeq6eATucjv8',
    appId: '1:557760880908:web:ef9fe4b835aad8b5c42929',
    messagingSenderId: '557760880908',
    projectId: 'bharatnova-8de12',
    authDomain: 'bharatnova-8de12.firebaseapp.com',
    storageBucket: 'bharatnova-8de12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgoMIWBrTC-be7kKGN34LG4LjRqbXqc8',
    appId: '1:557760880908:android:4912280b2fab124fc42929',
    messagingSenderId: '557760880908',
    projectId: 'bharatnova-8de12',
    storageBucket: 'bharatnova-8de12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWu1YKfWvho7b8shp2aXYsSDaTTxHQghM',
    appId: '1:557760880908:ios:bf65fe340982bf72c42929',
    messagingSenderId: '557760880908',
    projectId: 'bharatnova-8de12',
    storageBucket: 'bharatnova-8de12.firebasestorage.app',
    iosBundleId: 'com.gobi.bharatnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWu1YKfWvho7b8shp2aXYsSDaTTxHQghM',
    appId: '1:557760880908:ios:bf65fe340982bf72c42929',
    messagingSenderId: '557760880908',
    projectId: 'bharatnova-8de12',
    storageBucket: 'bharatnova-8de12.firebasestorage.app',
    iosBundleId: 'com.gobi.bharatnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0j7rUIoFvnW7jEtX_JOiOeq6eATucjv8',
    appId: '1:557760880908:web:3fcb0889f2a420ddc42929',
    messagingSenderId: '557760880908',
    projectId: 'bharatnova-8de12',
    authDomain: 'bharatnova-8de12.firebaseapp.com',
    storageBucket: 'bharatnova-8de12.firebasestorage.app',
  );
}
